### ISSUE TITLE
能不能給個接口表

### ISSUE THREAD

**Issue by TommcyOWO** [FlowerEatFish/books-com-tw-api#2]
剛好發現網路上沒有相對應的py 爬蟲example 
想自己搞一個
謝謝

**Comment by FlowerEatsFish** [comment]
- 如果是指官方（博客來）的話，官方沒有提供接口表，所以才會製作這個爬蟲工具。

  個人是使用這段 URL 去取得資源，再解析並轉換成個人想要的格式。

  `GET https://search.books.com.tw/search/query/cat/all/sort/1/v/0/ms2/ms2_1/page/{page}/key/{keyword}`

  Request Path Parameters

  |Parameter|Type|Required|Description|
  |--------|---|---|---|
  |page|Integer|Yes|頁碼|
  |keyword|String|Yes|關鍵字|

  範例：[`https://search.books.com.tw/search/query/cat/all/sort/1/v/0/ms2/ms2_1/page/1/key/python`](https://search.books.com.tw/search/query/cat/all/sort/1/v/0/ms2/ms2_1/page/1/key/python)

  ([ref](https://github.com/FlowerEatsFish/books-com-tw-crawler/blob/v1.2.0/src/books-com-tw-fetch.ts#L37))

- 如果是指這個爬蟲工具的返回格式：

  Response Body

  |Field|Type|Nullable|Description|
  |---|---|---|---|
  |title|String|Yes|標題|
  |author|String[]|Yes|作者|
  |publisher|String|Yes|出版社|
  |publicationDate|String|Yes|出版日期|
  |imageUrl|String|Yes|書封連結|
  |introduction|String|Yes|摘要|
  |price|Object|No|價格資訊|
  |price.discount|Integer|Yes|折扣率（9 折 = 9, 85 折 = 85）|
  |price.currentPrice|Integer|Yes|折後價格|
  |url|String|Yes|網址|

  Response Codes

  |Code|Description|
  |---|---|
  |200|OK|
  |404|Not Found|

  ([ref](https://github.com/FlowerEatsFish/books-com-tw-crawler/blob/v1.2.0/index.d.ts#L1-L15))

**Comment by TommcyOWO** [comment]
謝謝
