### ISSUE TITLE
能不能給個接口

### ISSUE THREAD

**Issue by TommcyOWO** [FlowerEatFish/books-com-tw-api#3]
我想要做個爬蟲，我希望拿到接口表
OWO

**Comment by FlowerEatsFish** [comment]
https://github.com/FlowerEatsFish/books-com-tw-crawler/issues/2#issuecomment-1680684525 有回答到你的問題嗎？

我只有使用這個接口而已，而且返回的資料是一個 HTML 頁面。

其他接口我沒去使用，也沒有整理成表。

`GET https://search.books.com.tw/search/query/cat/all/sort/1/v/0/ms2/ms2_1/page/{page}/key/{keyword}`

Request Path Parameters

|Parameter|Type|Required|Description|
|--------|---|---|---|
|page|Integer|Yes|頁碼|
|keyword|String|Yes|關鍵字|

範例：[`https://search.books.com.tw/search/query/cat/all/sort/1/v/0/ms2/ms2_1/page/1/key/python`](https://search.books.com.tw/search/query/cat/all/sort/1/v/0/ms2/ms2_1/page/1/key/python)

**Comment by TommcyOWO** [comment]
o fk 忘記問過了
OAO 
抱歉打擾
